### ISSUE TITLE
Question:The old plugin always inserts the css file at the top of the head tag.

### ISSUE THREAD

**Issue by linmodev** [wix-playground/stylable-webpack-plugin#11]
The old plugin always inserts the css file at the top of the head tag, and the following is the style that I refer to by other ui components. I often need to override their style, but the old plugin always compiles the .st.css file. Generated css inserted to the top

![image](https://user-images.githubusercontent.com/21982105/40339672-06d6254e-5dae-11e8-9ad9-4ac5ed79bc4d.png)
@barak007

**Comment by idoros** [comment]
Just to clarify, 

the new integration puts the bundled CSS before any other custom stylesheets? would you like it to be after? 

Is this project open so we can see it? or can you provide the configuration you use?

**Comment by linmodev** [comment]
```javascript
rules: [
      {
        oneOf: [
          StylablePlugin.rule(),
          {
            test: /\.tsx?$/,
            exclude: /node_modules/,
            use: [
              { loader: "cache-loader" },
              // {
              //   loader: "thread-loader",
              //   options: {
              //     // there should be 1 cpu for the fork-ts-checker-webpack-plugin
              //     workers: require("os").cpus().length - 1
              //   }
              // },
              { loader: "react-hot-loader/webpack" },
              {
                loader: "ts-loader",
                options: {
                  // transpileOnly: true,
                  happyPackMode: true, // IMPORTANT! use happyPackMode mode to speed-up compilation and reduce errors reported to webpack
                  getCustomTransformers: () => ({
                    before: [
                      tsImportPluginFactory({
                        style: true
                      })
                    ]
                  }),
                  compilerOptions: {
                    module: "esnext"
                  }
                }
              }
            ]
          },
          {
            test: /\.less$/,
            oneOf: [
              {
                use: [
                  {
                    loader: "style-loader"
                  },
                  {
                    loader: "css-loader",
                    options: {
                      sourceMap: true
                    }
                  },
                  {
                    loader: "less-loader",
                    options: {
                      javascriptEnabled: true,
                      modifyVars: theme,
                      sourceMap: true
                    }
                  }
                ]
              }
            ]
          },
          {
            test: /(?!\.st)\.css$/,
            use: [
              {
                loader: "style-loader"
              },
              {
                loader: "css-loader",
                options: {
                  sourceMap: true
                }
              }
            ]
          },

          {
            test: /\.(jpe?g|png|gif)$/i,
            use: [
              {
                loader: "file-loader",
                options: {
                  hash: "sha512",
                  digest: "hex",
                  name: "[hash].[ext]"
                }
              },
              {
                loader: "image-webpack-loader",
                options: {
                  query: {
                    mozjpeg: {
                      progressive: true
                    },
                    gifsicle: {
                      interlaced: false
                    },
                    optipng: {
                      optimizationLevel: 4
                    },
                    pngquant: {
                      quality: "75-90",
                      speed: 3
                    }
                  }
                }
              }
            ]
          }
        ]
      }
    ]
```
The above code is my configuration, I tried a variety of orders, but the StylablePlugin is always the first time to insert main.css into the html head tag. And when I change the order, I will also report various errors. For example, the oneOf is necessary. I cannot write loaders directly in the rules.
@idoros

**Comment by linmodev** [comment]
@idoros I tried to upgrade to webpack4 but some of the plugins are in conflict, so I went back to the original version later. If the new plugin can customize the placement, I'd certainly be happy to use it. I like the Stylable project very much, but I feel that it's a problem. There are too few people who contribute code, so there is no way to solve the problem.

**Comment by idoros** [comment]
First of all let me agree that the transition from Webpack v3 to v4 has been tough. but at the moment it seems that most of the ecosystem has moved on, and its incredibly hard to stay behind. So with no relation to Stylable, I recommend upgrading to v4.

We will be stopping support for our Webpack v3 integration in the near future, but even with the next version, I'm not sure I understand what you are trying to do. I see you are using Stylable, CSS modules, LESS and JSS. How are they "extending" each other or operate together?

I would love to help, but I need a working example of the project in order to see whats going on.
Can you describe your build pipeline flow? or provide a more extensive reference for your project?

**Comment by linmodev** [comment]
@idoros 
For reproduce this issue, I upload a simple project. 
Step: 
> 1 `npm install `
>2  `npm start`


https://github.com/linmodev/reproduce/tree/master/StylableWebpackPlugin
Note:
This project has three webpack config files.
* `webpack.config.dev.js` can work well.
* `webpack.config.dev2.js` has some errors like under picture show.
![image](https://user-images.githubusercontent.com/21982105/40402055-28594fec-5e7c-11e8-9a9c-c9a49fe36af4.png)
* `webpack.config.dev3.js` has some errors like under picture show.
![image](https://user-images.githubusercontent.com/21982105/40402105-74611c26-5e7c-11e8-95d4-5b1fe847b90d.png)
I have to say that it is really troublesome to reproduce this problem

**Comment by idoros** [comment]
a few things to try:

1. your condition to filter out `.st.css` files seems broken. You can see in `config.dev3` that the result stylesheet modules go through `style-loader`. try changing the options of `style-loader` to:
```
test: /\.css$/,
exclude: [/\.st\.css/]
```

2. the order of `oneOf` or Webpack rules have no affect on the order of result style/link tags. But `style-loader` has some [options](https://github.com/webpack-contrib/style-loader#insertat) to control. Try changing 'inserAt' if you want Stylable to be after other generated CSS.

**Comment by idoros** [comment]
happy to help :)
