### ISSUE TITLE
runtime code is not transpiled causing bugs with IE11

### ISSUE THREAD

**Issue by ranyitz** [wix-playground/stylable-webpack-plugin#6]
`stylable-webpack-plugin` is inserting an untranspiled code to the bundle which is causing runtime errors to people that try to use it.

For example look at [this bundle](https://static.parastorage.com/services/business-manager/1.621.0/app.bundle.js) and search for stylable.

This bug is stopping a lot of teams from migrating to `yoshi@2`.

**Comment by barak007** [comment]
fixed in v1.0.5
