### ISSUE TITLE
TypeError: chunk.entryModule is undefined

### ISSUE THREAD

**Issue by hepiyellow** [wix-playground/stylable-webpack-plugin#7]
The error
---------
```
/Users/erezm/Projects/wix-ui/packages/wix-ui-core/node_modules/stylable-webpack-plugin/src/StylableBootstrapModule.js:85
    const dep = new StylableImportDependency(module.request, {
                                                    ^
TypeError: Cannot read property 'request' of undefined
```
How to reproduce:
-----------------
It happens in wix-ui-core after upgrading to yoshi 2.1.3,
And following the migration guide:
https://github.com/wix-private/fed-handbook/wiki/Yoshi-2.0#i-have-a-storybook-configuration-which-runs-using-webpack-3

This error happens when running  storybook’s ‘build_storybook'.
You can checkout this branch : https://github.com/wix/wix-ui/tree/yoshi_2
and run: 
```
cd packages/wix-ui-core
npm install
npm run build
npm run pretest
```

Analysis
--------
Looking into it, we discovered that in this line the chunk.entryModule sometimes is undefined.
In my example this line runs 2 times, once with a chunk called ‘preview’ in which entryModule is defined. And a second time with a chunk called vendor~preview in which the entryModule is NOT defined.

We tried Not to addStylableModuleDependenty when the entryModule is undefined, and our build_storybook passed (not sure yet if the results are proper).

**Comment by barak007** [comment]
Fixed in v1.0.7
